package com.example.Alching;

public enum AlchState {
    BUYITEM1,
    BUYITEM2,
    BUYITEM3,
    CHECKING_INVENTORY,
    ALCHING_ITEM_ONE,
    ALCHING_ITEM_TWO,
    ALCHING_ITEM_THREE,
    OPEN_GE,
    ALCHING_ITEM_ONE_NOTE,
    ALCHING_ITEM_THREE_NOTE,
    ALCHING_ITEM_TWO_NOTE,
    BUY_NATURE_RUNES,
    ALCHING,
    GATHER_ITEMS,
    GET_LVL_55_MAGIC, BREAK
}
