package com.example.AutoFarmRun;

public enum AutoFarmRunState {
    TESTING,
    CATHERBY_PATCH,
    CIVITAS_ILLA_FORTIS_PATCH,
    FALADOR_PATCH,
    FARMING_GUILD_PATCH,
    HARMONY_PATCH,
    KOUREND_PATCH,
    MORYTANIA_PATCH,
    TROLL_STRONGHOLD_PATCH,
    WEISS_PATCH,
    HANDLING_HERB_PATCH,
    PLANTING_SEEDS,
    HERB_IS_GROWING,
    HERB_IS_FULLY_GROWN,
    HERB_IS_DEAD,
    HERB_IS_NOT_GROWING,
    USE_SEED,
    ARDYPATCH
}
